config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  devise_scope :user do 
    get 'after_signup_page', to: 'devise/registrations#after_signup' 
  end 
  devise_for :users , controllers: {registrations: "users/registrations", confirmations: "users/confirmations"}
  resources :expenses
  resources :incomes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :user 
end

app/models/income.rb
class Income < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable 

  has_many :expenses 
  has_many :incomes 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

    def show
        render 'confirmations/index'
    end  

    def after_confirmation_path_for(resource_name, resource)
        sign_in(resource)
        #render json: {"confirmation": "Sent!"}
    end 
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_user.expenses
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    #@expense = Expense.new
    @expense = current_user.expenses.build
    #@expense = current_user.expenses.create(attrs)
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    #@expense = Expense.new(expense_params)
    @expense = current_user.expenses.build(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount, :description)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = current_user.incomes
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    #@income = Income.new
    @income = current_user.incomes.build
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    #@income = Income.new(income_params)
    @income = current_user.incomes.build(income_params)
    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:title, :amount, :description)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
     super do
       sign_in(resource) if resource.errors.empty? 
     end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  #def after_confirmation_path_for(resource_name, resource)
     #super(resource_name, resource)
  #   sign_in(resource)
  #end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true


require 'recaptcha'

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  private
   def check_captcha
    unless  verify_recaptcha
      self.resource = resource_class.new sign_up_params
      resource.validate # Look for any other validation errors besides Recaptcha
      set_minimum_password_length
      respond_with_navigational(resource) { render :new }
      
    end
   end
  
  protected
  def after_inactive_sign_up_path_for(resource)
    '/after_signup_page'
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, 'عنوان' %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :amount, 'مبلغ' %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :description, 'توضیحات' %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit, 'ایجاد خرج جدید' %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'نمایش', @expense %> |
<%= link_to 'بازگشت', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>مخارج</h1>

<table>
  <thead>
    <tr>
      <th>عنوان</th>
      <th>مبلغ</th>
      <th>توضیحات</th>
      <th>تاریخ </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.title %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.description %></td>
        <td><%= JalaliDate.new(Date.parse(expense.created_at.to_s))%></td>
        <td><%= link_to 'نمایش', expense %></td>
        <td><%= link_to 'ویرایش', edit_expense_path(expense) %></td>
        <td><%= link_to 'حذف', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'خرج جدید', new_expense_path %>
<% if user_signed_in? %>
    <ul>
     <li><%= link_to 'بازگشت', root_path =%>
     <li><%= link_to 'حساب کاربری', edit_user_registration_path %></li>
     <li><%= link_to 'خروج', destroy_user_session_path, :method => :delete %></li>
    </ul>
   <% else %>
    <ul>
     <li><%= link_to 'ایجاد حساب کاربری', new_user_registration_path%></li>
     <li><%= link_to 'ورود', new_user_session_path %></li>
    </ul>
   <% end %>

app/views/expenses/new.html.erb
<h1>خرج جدید</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>عنوان: </strong>
  <%= @expense.title %>
</p>

<p>
  <strong>مبلغ: </strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>توضیحات: </strong>
  <%= @expense.description %>
</p>

<p>
  <strong> تاریخ: </strong>
  <%= JalaliDate.new(Date.parse(@expense.created_at.to_s)) %>
</p>

<%= link_to 'ویرایش', edit_expense_path(@expense) %> |
<%= link_to 'بازگشت', expenses_path %>

app/views/incomes/_form.html.erb
<%= form_with(model: income, local: true) do |form| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, 'عنوان' %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :amount, 'مبلغ' %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :description, 'توضیحات' %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit, 'ایجاد درآمد جدید' %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'نمایش', @income %> |
<%= link_to 'بازگشت', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>درآمدها</h1>

<table>
  <thead>
    <tr>
      <th>عنوان</th>
      <th>مبلغ</th>
      <th>توضیحات</th>
      <th> تاریخ </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.title %></td>
        <td><%= income.amount %></td>
        <td><%= income.description %></td>
        <td><%= JalaliDate.new(Date.parse(income.created_at.to_s)) %></td>
        <td><%= link_to 'نمایش', income %></td>
        <td><%= link_to 'ویرایش', edit_income_path(income) %></td>
        <td><%= link_to 'حذف', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'درآمد جدید', new_income_path %>
<% if user_signed_in? %>
    <ul>
     <li><%= link_to 'بازگشت', root_path =%>
     <li><%= link_to 'حساب کاربری', edit_user_registration_path %></li>
     <li><%= link_to 'خروج', destroy_user_session_path, :method => :delete %></li>
    </ul>
   <% else %>
    <ul>
     <li><%= link_to 'ایجاد حساب کاربری', new_user_registration_path%></li>
     <li><%= link_to 'ورود', new_user_session_path %></li>
    </ul>
   <% end %>

app/views/incomes/new.html.erb
<h1>ثبت درآمد جدید</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>عنوان: </strong>
  <%= @income.title %>
</p>

<p>
  <strong>مبلغ: </strong>
  <%= @income.amount %>
</p>

<p>
  <strong>توضیحات: </strong>
  <%= @income.description %>
</p>
<p>
  <strong> تاریخ: </strong>
  <%= JalaliDate.new(Date.parse(@income.created_at.to_s)) %>
</p>

<%= link_to 'ویرایش', edit_income_path(@income) %> |
<%= link_to 'بازگشت', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<html>
  <head>
    <title>سامانه مدیریت دخل و خرج</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> سامانه مدیریت دخل و خرج </h1>

<% if !user_signed_in? %>
<p class="error-message">
    کاربر گرامی، به سامانه مدیریت دخل و خرج خوش آمدید. لطفا جهت استفاده از امکانات ما وارد شوید یا یک حساب کاربری جدید ایجاد کنید.
</p>
<ul>
     <li><%= link_to 'ایجاد حساب کاربری', new_user_registration_path%></li>
     <li><%= link_to 'ورود', new_user_session_path %></li>
</ul>
<% else %> 
<h1 class="welcome-message"> خوش آمدید! </h1>
<div class="user-property">
 <div class="user-block">
  <h2> درآمدها </h2>
  <table>
   <thead>
   <tr>
    <th><strong> عنوان </strong></th>
    <th><strong> مبلغ </strong></th>
    <th><strong>  تاریخ </strong></th>
    <th colspan="3"></th>
   </tr>
   </thead>
   <tbody>
    <% current_user.incomes.each do |income| %>
    <tr>
     <td><%= income.title %></td>
     <td><%= income.amount %></td> 
     <td><%= JalaliDate.new(Date.parse(income.created_at.to_s)) %>
    </tr> 
    <% end %>
   </tbody>
  </table>
    <a class="link-to" href="/incomes"> صفحه مدیریت درآمدها </a>
 </div>
 <div class="user-block">
   <h2> مخارج </h2>
   <table>
   <thead>
   <tr>
    <th><strong> عنوان </strong></th>
    <th><strong> مبلغ </strong></th>
    <th><strong>  تاریخ </strong></th>
    <th colspan="3"></th>
   </tr>
   </thead>
   <tbody>
    <% current_user.expenses.each do |expense| %>
    <tr>
     <td><%= expense.title %></td>
     <td><%= expense.amount %></td> 
     <td><%= JalaliDate.new(Date.parse(expense.created_at.to_s)) %>
    </tr> 
    <% end %>
  </table>
  <a class="link-to" href="/expenses"> صفحه مدیریت مخارج </a>
 </div>
</div>
<div class="end-of-page">
<%= link_to 'خروج', destroy_user_session_path, :method => :delete %></li>
</div>
<% end %>